"Async CMD server acknowledge"
type CommandAck {
   "message accepted by the server"
   accepted: Boolean
}

type ClientProfile {
   clientId: String
   name: String
   username: String
}

type Query {
   "Get profile data of the logged user"
   ClientProfile: ClientProfile @requireAuth     
}

type Mutation {
   validateNewClient: ClientProfile @requireAuth
}
