"Async CMD server acknowledge"
type CommandAck {
   "message accepted by the server"
   accepted: Boolean
}

type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

type ClientData {
   "Client id"
   clientId: String
   "Client name"
   name: String
   "Client username"
   username: String
   "SatelliteID"
   satelliteId: String
}

type Query {
   "Get profile data of the logged user"
   ClientProfile: ClientData @requireAuth     
}

type Mutation {
   ValidateNewClient: ClientData @requireAuth
   linkSatellite(satelliteId: String): CommandResponse
}
